version: '3'
services:
  database:
    image: "postgres:10"
    ports:
      - 15433:5432
    environment:
      - POSTGRES_DB=parking_dev
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
volumes:
  postgres: